name: ARTIFACT UPLOAD

on:
  workflow_dispatch:

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: build/libs/*.jar
